//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace breederhub.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        public int DogId { get; set; }
        public int Breed_FK { get; set; }
        public System.DateTime DOB { get; set; }
        public string Name { get; set; }
        public string KCNumber { get; set; }
        public Nullable<int> Gender { get; set; }
    }
}
