//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace breederhub.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Litter
    {
        public int LitterId { get; set; }
        public int Dame_FK { get; set; }
        public int Sire_FK { get; set; }
        public int Puppy_FK { get; set; }
    }
}
